services:
  mongodb:
    image: mongo:7.0.24
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data
    restart: unless-stopped
    
  wiremock:
    pull_policy: always
    environment:
      TZ: Europe/London
    image: sheyenrath/wiremock.net:latest
    ports:
      - "9090:80"    

  api:
    build:
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_started
      wiremock:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Mongo__DatabaseUri: mongodb://mongodb:27017/
      PORT: 8080
      AWS_EMF_ENABLED: false
      AWS_EMF_ENVIRONMENT: Local
      # See appsettings.json for additional settings related to auth
      PrnCommonBackend__TokenEndpoint: http://wiremock/oauth2/v2.0/token
      PrnCommonBackend__BaseAddress: http://wiremock/
      WasteOrganisations__BaseAddress: http://wiremock/
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/all"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  mongodb-data:
